name: py_clifford_dev
channels:
  - conda-forge
  - adelaneh
  - defaults
  - intel
dependencies:
    - setuptools
    - pandas
    - nose
    - numpy==1.16
    - matplotlib
    - tensorflow==1.15.2
    - tqdm
